# Generated by Django 4.x on 2025-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Define any dependencies here, such as previous migrations
    ]

    operations = [
        migrations.CreateModel(
            name='CipsPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_url', models.CharField(max_length=255)),
                ('merchant_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('validation_url', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('creditor_password', models.CharField(max_length=255)),
                ('creditor_pfx_file', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
